import { asRecord, safeJson } from "../util/records.js";
import { raceWithAbort } from "../files/cancel.js";

export type OpenRouterContentPart =
  | { type: "text"; text: string }
  | { type: "image_url"; image_url: { url: string; detail?: "auto" | "low" | "high" } };

export interface OpenRouterToolCall {
  id: string;
  type: "function";
  function: { name: string; arguments: string };
}

export interface OpenRouterMessage {
  role: "system" | "user" | "assistant" | "tool";
  content: string | OpenRouterContentPart[] | null;
  tool_call_id?: string;
  tool_calls?: OpenRouterToolCall[];
  /** Provider reasoning blocks must be returned unchanged between tool steps. */
  reasoning_details?: unknown[];
}

export interface OpenRouterToolResult {
  content: OpenRouterContentPart[];
  isError?: boolean;
  completed?: boolean;
  terminate?: boolean;
  details?: unknown;
}

export interface OpenRouterTool {
  name: string;
  description: string;
  parameters: Record<string, unknown>;
  execute(input: unknown, signal?: AbortSignal, callId?: string): Promise<OpenRouterToolResult | unknown>;
}

export interface OpenRouterUsageCall {
  provider: string;
  model: string;
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  reasoningTokens?: number;
  cost?: { input: number; output: number; cacheRead: number; cacheWrite: number; total: number };
}

export interface OpenRouterUsage {
  inputTokens: number;
  outputTokens: number;
  cacheReadTokens: number;
  cacheWriteTokens: number;
  totalTokens: number;
  cacheReadRatio: number | null;
  calls: OpenRouterUsageCall[];
}

export interface OpenRouterTurnResult {
  text: string;
  /** Only messages generated by this turn, suitable for appending to history. */
  messages: OpenRouterMessage[];
  usage: OpenRouterUsage;
  model: string;
}

export class OpenRouterError extends Error {
  partial?: OpenRouterTurnResult;
  constructor(message: string, readonly status?: number, readonly code?: string | number, options?: ErrorOptions) {
    super(message, options);
    this.name = "OpenRouterError";
  }
}

export interface OpenRouterTurnInput {
  apiKey: string;
  model: string;
  messages: OpenRouterMessage[];
  tools?: OpenRouterTool[];
  signal?: AbortSignal;
  maxModelCycles?: number;
  maxToolCalls?: number;
  requestTimeoutMs?: number;
  reasoningEffort?: string;
  onText?: (delta: string) => void | Promise<void>;
  onToolCall?: (call: OpenRouterToolCall) => void | Promise<void>;
  onToolResult?: (call: OpenRouterToolCall, result: OpenRouterToolResult) => void | Promise<void>;
  onUsage?: (usage: OpenRouterUsage) => void | Promise<void>;
  fetch?: (input: string, init: RequestInit) => Promise<Response>;
}

/** A deliberately small fallback loop; native Codex owns the primary harness. */
export async function runOpenRouterTurn(input: OpenRouterTurnInput): Promise<OpenRouterTurnResult> {
  const generated: OpenRouterMessage[] = [];
  const calls: OpenRouterUsageCall[] = [];
  let text = "";
  let model = input.model;
  let toolCalls = 0;
  const snapshot = (): OpenRouterTurnResult => ({ text, messages: [...generated], usage: aggregateUsage(calls), model });
  const tools = new Map((input.tools ?? []).map(tool => [tool.name, tool]));
  try {
    input.signal?.throwIfAborted();
    if (!input.apiKey.trim()) throw new OpenRouterError("OpenRouter fallback is not configured.");
    const maxModelCycles = input.maxModelCycles === 0 ? Infinity : input.maxModelCycles ?? 24;
    const maxToolCalls = input.maxToolCalls === 0 ? Infinity : input.maxToolCalls ?? 64;
    for (let cycle = 0; cycle < maxModelCycles; cycle++) {
      input.signal?.throwIfAborted();
      const assistant: OpenRouterMessage = { role: "assistant", content: "" };
      generated.push(assistant);
      const response = await requestCompletion(input, [...input.messages, ...generated.slice(0, -1)], tools);
      let usage: Record<string, unknown> | undefined;
      const pending = new Map<number, OpenRouterToolCall>();
      let finished = false;
      try {
        for await (const event of streamEvents(response, input.signal)) {
          if (event === "[DONE]") { finished = true; break; }
          let chunk: Record<string, unknown> | undefined;
          try { chunk = asRecord(JSON.parse(event)); }
          catch { throw new OpenRouterError("OpenRouter returned malformed streaming data."); }
          if (!chunk) throw new OpenRouterError("OpenRouter returned invalid streaming data.");
          const error = asRecord(chunk.error);
          if (error) throw providerError(error);
          if (typeof chunk.model === "string") model = chunk.model;
          usage = asRecord(chunk.usage) ?? usage;
          const choice = asRecord(Array.isArray(chunk.choices) ? chunk.choices[0] : undefined);
          const delta = asRecord(choice?.delta);
          if (typeof choice?.finish_reason === "string") {
            if (choice.finish_reason === "error") throw new OpenRouterError("OpenRouter generation failed.");
            finished = true;
          }
          if (typeof delta?.content === "string" && delta.content) {
            assistant.content = String(assistant.content ?? "") + delta.content;
            text += delta.content;
            await input.onText?.(delta.content);
          }
          if (Array.isArray(delta?.reasoning_details)) {
            assistant.reasoning_details = mergeReasoning(assistant.reasoning_details ?? [], delta.reasoning_details);
          }
          for (const raw of Array.isArray(delta?.tool_calls) ? delta.tool_calls : []) {
            const part = asRecord(raw);
            if (!part || !Number.isInteger(part.index) || Number(part.index) < 0) throw new OpenRouterError("Invalid streamed tool call.");
            const index = Number(part.index);
            const call = pending.get(index) ?? { id: "", type: "function", function: { name: "", arguments: "" } };
            if (typeof part.id === "string") call.id += part.id;
            const fn = asRecord(part.function);
            if (typeof fn?.name === "string") call.function.name += fn.name;
            if (typeof fn?.arguments === "string") call.function.arguments += fn.arguments;
            pending.set(index, call);
            assistant.tool_calls = [...pending].sort(([a], [b]) => a - b).map(([, value]) => value);
          }
        }
      } finally {
        if (usage) {
          calls.push(normalizeUsage(usage, model));
          await input.onUsage?.(aggregateUsage(calls));
        }
      }
      if (!finished) throw new OpenRouterError("OpenRouter disconnected before completing its response.");
      const requested = assistant.tool_calls ?? [];
      if (!requested.length) return snapshot();
      if (requested.some(call => !call.id || !call.function.name)) throw new OpenRouterError("OpenRouter returned an incomplete tool call.");
      if (toolCalls + requested.length > maxToolCalls) throw new OpenRouterError("OpenRouter fallback tool limit reached.");
      const mixedFinish = requested.length > 1 && requested.some(call => call.function.name === "finish_response");
      const images: OpenRouterContentPart[] = [];
      let completed = false;
      for (const call of requested) {
        input.signal?.throwIfAborted();
        toolCalls++;
        await input.onToolCall?.(call);
        let result: OpenRouterToolResult;
        try {
          if (mixedFinish) throw new Error("finish_response must be the sole tool in its response. No tools in this batch ran; finish other work first.");
          const tool = tools.get(call.function.name);
          if (!tool) throw new Error(`Unknown tool: ${call.function.name}`);
          const args: unknown = JSON.parse(call.function.arguments || "{}");
          result = toolResult(await raceWithAbort(tool.execute(args, input.signal, call.id), input.signal));
        } catch (error) {
          input.signal?.throwIfAborted();
          result = { content: [{ type: "text", text: safeJson({ error: error instanceof Error ? error.message : String(error) }) }], isError: true };
        }
        generated.push({ role: "tool", tool_call_id: call.id, content: result.content.filter(part => part.type === "text").map(part => part.text).join("\n") });
        const returnedImages = result.content.filter(part => part.type === "image_url");
        if (returnedImages.length) images.push({ type: "text", text: `Images returned by ${call.function.name} (${call.id}):` }, ...returnedImages);
        completed ||= !result.isError && (result.completed === true || result.terminate === true || asRecord(result.details)?.completed === true);
        await input.onToolResult?.(call, result);
      }
      if (images.length) generated.push({ role: "user", content: images });
      if (completed) return snapshot();
    }
    throw new OpenRouterError("OpenRouter fallback model cycle limit reached.");
  } catch (error) {
    input.signal?.throwIfAborted();
    const failure = error instanceof OpenRouterError ? error : new OpenRouterError(error instanceof Error ? error.message : String(error), undefined, undefined, { cause: error });
    failure.partial = snapshot();
    throw failure;
  }
}

async function requestCompletion(input: OpenRouterTurnInput, messages: OpenRouterMessage[], tools: Map<string, OpenRouterTool>): Promise<Response> {
  const signal = AbortSignal.any([...(input.signal ? [input.signal] : []), AbortSignal.timeout(input.requestTimeoutMs ?? 180_000)]);
  const response = await (input.fetch ?? fetch)("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: { Authorization: `Bearer ${input.apiKey}`, "Content-Type": "application/json", "X-Title": "ai-tg-bot" },
    body: JSON.stringify({ model: input.model, messages, stream: true, stream_options: { include_usage: true },
      ...(tools.size ? { tools: [...tools.values()].map(tool => ({ type: "function", function: { name: tool.name, description: tool.description, parameters: tool.parameters } })) } : {}),
      ...(input.reasoningEffort ? { reasoning: { effort: input.reasoningEffort } } : {}),
    }), signal,
  });
  if (!response.ok) {
    const body: unknown = await response.json().catch(() => undefined);
    throw providerError(asRecord(asRecord(body)?.error), response.status);
  }
  if (!response.body) throw new OpenRouterError("OpenRouter returned an empty response body.");
  return response;
}

async function* streamEvents(response: Response, signal?: AbortSignal): AsyncGenerator<string> {
  const reader = response.body!.getReader();
  const decoder = new TextDecoder();
  let pending = "";
  let data: string[] = [];
  const onAbort = () => { void reader.cancel(signal?.reason).catch(() => undefined); };
  signal?.addEventListener("abort", onAbort, { once: true });
  try {
    for (;;) {
      signal?.throwIfAborted();
      const next = await reader.read();
      signal?.throwIfAborted();
      pending += decoder.decode(next.value, { stream: !next.done });
      if (pending.length > 4 * 1024 * 1024) throw new OpenRouterError("OpenRouter streaming event exceeded its size limit.");
      let boundary: number;
      while ((boundary = pending.indexOf("\n")) >= 0) {
        const line = pending.slice(0, boundary).replace(/\r$/, "");
        pending = pending.slice(boundary + 1);
        if (!line) {
          if (data.length) { yield data.join("\n"); data = []; }
        } else if (line.startsWith("data:")) {
          data.push(line.slice(5).replace(/^ /, ""));
        }
      }
      if (next.done) break;
    }
    if (pending.startsWith("data:")) data.push(pending.slice(5).replace(/^ /, ""));
    if (data.length) yield data.join("\n");
  } finally {
    signal?.removeEventListener("abort", onAbort);
    await reader.cancel().catch(() => undefined);
    reader.releaseLock();
  }
}

function providerError(error?: Record<string, unknown>, status?: number): OpenRouterError {
  const code = typeof error?.code === "number" || typeof error?.code === "string" ? error.code : undefined;
  return new OpenRouterError(typeof error?.message === "string" ? error.message.slice(0, 1000) : `OpenRouter request failed${status ? `: HTTP ${status}` : "."}`, status, code);
}

function toolResult(value: unknown): OpenRouterToolResult {
  const record = asRecord(value);
  if (Array.isArray(record?.content)) return value as OpenRouterToolResult;
  return { content: [{ type: "text", text: safeJson(value) }], details: value, isError: typeof record?.error === "string", completed: record?.completed === true };
}

function mergeReasoning(previous: unknown[], updates: unknown[]): unknown[] {
  const result = [...previous];
  for (const update of updates) {
    const next = asRecord(update);
    const index = next?.index;
    const position = typeof index === "number" ? result.findIndex(part => asRecord(part)?.index === index) : -1;
    if (position < 0) { result.push(update); continue; }
    const before = asRecord(result[position]);
    const merged = { ...before, ...next };
    for (const key of ["text", "summary", "data"]) {
      if (typeof before?.[key] === "string" && typeof next?.[key] === "string") merged[key] = before[key] + next[key];
    }
    result[position] = merged;
  }
  return result;
}

function count(value: unknown): number { return typeof value === "number" && Number.isFinite(value) ? Math.max(0, value) : 0; }

function normalizeUsage(usage: Record<string, unknown>, model: string): OpenRouterUsageCall {
  const prompt = count(usage.prompt_tokens);
  const details = asRecord(usage.prompt_tokens_details);
  const cacheReadTokens = Math.min(prompt, count(details?.cached_tokens));
  const cacheWriteTokens = Math.min(prompt - cacheReadTokens, count(details?.cache_write_tokens));
  return { provider: "openrouter", model, inputTokens: prompt - cacheReadTokens - cacheWriteTokens, outputTokens: count(usage.completion_tokens), cacheReadTokens, cacheWriteTokens,
    reasoningTokens: count(asRecord(usage.completion_tokens_details)?.reasoning_tokens),
    ...(typeof usage.cost === "number" ? { cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: count(usage.cost) } } : {}),
  };
}

function aggregateUsage(calls: OpenRouterUsageCall[]): OpenRouterUsage {
  const total = calls.reduce((sum, call) => ({ inputTokens: sum.inputTokens + call.inputTokens, outputTokens: sum.outputTokens + call.outputTokens, cacheReadTokens: sum.cacheReadTokens + call.cacheReadTokens, cacheWriteTokens: sum.cacheWriteTokens + call.cacheWriteTokens }), { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0 });
  const prompt = total.inputTokens + total.cacheReadTokens + total.cacheWriteTokens;
  return { ...total, totalTokens: prompt + total.outputTokens, cacheReadRatio: prompt ? Math.round(total.cacheReadTokens / prompt * 10_000) / 10_000 : null, calls: [...calls] };
}
