#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

REPO_ROOT=$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE=/dev/null
POSTGRES_CLIENT_IMAGE="${POSTGRES_CLIENT_IMAGE:-postgres:17.10-bookworm}"
ARCHIVE_IMAGE="${ARCHIVE_IMAGE:-alpine:3.22}"
AUDIT_IMAGE="ai-tg-bot-upgrade-audit:export-$$"
SECRET_DIR=""
EXPORT_DIR=""
EXPORT_SUCCEEDED=0
SELECTED_VALUE=""

fail() {
  printf '\n%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
  exit 1
}

migration_banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "Unraid to Dokploy migration export" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '  This wizard reads the stopped bot configuration, writes one audit baseline,\n'
  printf '  and creates three verified upload files. It never starts or stops a container.\n'
  pause "Ready to start?"
}

cleanup() {
  local status=$?
  if [[ -n "$SECRET_DIR" && -d "$SECRET_DIR" ]]; then
    rm -f -- \
      "$SECRET_DIR/db-url" \
      "$SECRET_DIR/bot-token" \
      "$SECRET_DIR/pg-service.conf"
    rmdir -- "$SECRET_DIR" 2>/dev/null || true
  fi
  if [[ "$EXPORT_SUCCEEDED" != "1" && -n "$EXPORT_DIR" && -d "$EXPORT_DIR" ]]; then
    rm -f -- \
      "$EXPORT_DIR/.aibot.dump.partial" \
      "$EXPORT_DIR/.pi-home.tgz.partial" \
      "$EXPORT_DIR/.SHA256SUMS.partial" \
      "$EXPORT_DIR/aibot.dump" \
      "$EXPORT_DIR/pi-home.tgz" \
      "$EXPORT_DIR/SHA256SUMS"
    rmdir -- "$EXPORT_DIR" 2>/dev/null || true
  fi
  if [[ "$status" -ne 0 ]]; then
    printf '\nExport stopped. The wizard did not start or remove either source container.\n' >&2
  fi
  return "$status"
}

trap cleanup EXIT
trap 'exit 130' INT TERM

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required on the Unraid host."
}

container_env_value() {
  local container="$1" key="$2" line
  while IFS= read -r line; do
    if [[ "$line" == "$key="* ]]; then
      printf '%s' "${line#*=}"
      return 0
    fi
  done < <(docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' "$container")
  return 1
}

choose_value() {
  local prompt="$1"
  shift
  local values=("$@") choice index
  (( ${#values[@]} > 0 )) || fail "No choices are available for ${prompt}."
  printf '\n  %s\n' "$prompt"
  for index in "${!values[@]}"; do
    printf '    %s) %s\n' "$((index + 1))" "${values[$index]}"
  done
  if (( ${#values[@]} == 1 )); then
    printf '  Select [1]: '
  else
    printf '  Select [1-%s]: ' "${#values[@]}"
  fi
  read -r choice || true
  [[ -n "$choice" ]] || choice=1
  [[ "$choice" =~ ^[0-9]+$ ]] || fail "Selection must be a number."
  (( choice >= 1 && choice <= ${#values[@]} )) || fail "Selection is outside the displayed range."
  SELECTED_VALUE="${values[$((choice - 1))]}"
}

container_summary() {
  docker inspect --format '{{.Name}} | {{.Config.Image}} | {{.State.Status}}' "$1" | sed 's#^/##'
}

path_overlaps() {
  local left="${1%/}/" right="${2%/}/"
  [[ "$left" == "$right"* || "$right" == "$left"* ]]
}

mount_spec() {
  local type="$1" source="$2" target="$3" mode="${4:-}"
  [[ "$source" != *","* && "$source" != *$'\n'* ]] \
    || fail "The selected Pi mount source contains a character Docker --mount cannot represent safely."
  printf 'type=%s,source=%s,target=%s%s' "$type" "$source" "$target" "$mode"
}

if (( $# != 0 )); then
  printf '%s\n' "Usage: bash scripts/unraid-migration-wizard.sh" >&2
  exit 2
fi

migration_banner

stage "Check the Unraid host"
say "The old bot must already be stopped. PostgreSQL must stay running."
require_command docker
require_command sha256sum
docker info >/dev/null 2>&1 || fail "Docker is unavailable. Run this from an Unraid terminal with Docker access."
[[ -f "$REPO_ROOT/Dockerfile" && -f "$REPO_ROOT/scripts/upgrade-audit.ts" ]] \
  || fail "Run the wizard from a complete migration-branch checkout."
printf '  Export parent folder [%s]: ' "$PWD"
read -r export_parent_input || true
[[ -n "$export_parent_input" ]] || export_parent_input="$PWD"
[[ -d "$export_parent_input" && -w "$export_parent_input" ]] \
  || fail "The export parent folder must already exist and be writable."
EXPORT_PARENT=$(CDPATH='' cd -- "$export_parent_input" && pwd -P)
EXPORT_DIR="$EXPORT_PARENT/ai-tg-bot-migration-$(date -u +%Y%m%dT%H%M%SZ)"
[[ "$EXPORT_DIR" != *","* && "$EXPORT_DIR" != *$'\n'* ]] \
  || fail "The export path must not contain a comma or newline."
[[ ! -e "$EXPORT_DIR" ]] || fail "The timestamped export directory already exists. Wait one second and rerun."
say "Export folder: $EXPORT_DIR"

stage "Select the old containers"
mapfile -t ALL_CONTAINERS < <(docker ps -a --format '{{.Names}}')
(( ${#ALL_CONTAINERS[@]} > 0 )) || fail "Docker has no containers to inspect."
BOT_CANDIDATES=()
POSTGRES_CANDIDATES=()
for container in "${ALL_CONTAINERS[@]}"; do
  if [[ "$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/app/data/pi"}}yes{{end}}{{end}}' "$container")" == *yes* ]]; then
    BOT_CANDIDATES+=("$container")
  fi
  image=$(docker inspect --format '{{.Config.Image}}' "$container")
  if [[ "${image,,}" == *postgres* ]]; then
    POSTGRES_CANDIDATES+=("$container")
  fi
done
(( ${#BOT_CANDIDATES[@]} > 0 )) \
  || fail "No container has an exact /app/data/pi mount. Parent /app/data mounts are intentionally excluded."
(( ${#POSTGRES_CANDIDATES[@]} > 0 )) || fail "No PostgreSQL container was found."

BOT_CHOICES=()
for container in "${BOT_CANDIDATES[@]}"; do BOT_CHOICES+=("$(container_summary "$container")"); done
choose_value "Choose the stopped ai-tg-bot container:" "${BOT_CHOICES[@]}"
BOT_CHOICE="$SELECTED_VALUE"
for index in "${!BOT_CHOICES[@]}"; do
  [[ "${BOT_CHOICES[$index]}" == "$BOT_CHOICE" ]] && BOT_CONTAINER="${BOT_CANDIDATES[$index]}"
done

POSTGRES_CHOICES=()
for container in "${POSTGRES_CANDIDATES[@]}"; do POSTGRES_CHOICES+=("$(container_summary "$container")"); done
choose_value "Choose the running PostgreSQL container used by this bot:" "${POSTGRES_CHOICES[@]}"
POSTGRES_CHOICE="$SELECTED_VALUE"
for index in "${!POSTGRES_CHOICES[@]}"; do
  [[ "${POSTGRES_CHOICES[$index]}" == "$POSTGRES_CHOICE" ]] && POSTGRES_CONTAINER="${POSTGRES_CANDIDATES[$index]}"
done

[[ "$(docker inspect --format '{{.State.Running}}' "$BOT_CONTAINER")" == "false" ]] \
  || fail "The selected bot is still running. Stop it in the Unraid UI, then rerun the wizard."
[[ "$(docker inspect --format '{{.State.Running}}' "$POSTGRES_CONTAINER")" == "true" ]] \
  || fail "The selected PostgreSQL container is not running."
POSTGRES_HEALTH=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "$POSTGRES_CONTAINER")
[[ "$POSTGRES_HEALTH" == "none" || "$POSTGRES_HEALTH" == "healthy" ]] \
  || fail "The selected PostgreSQL container reports health status: $POSTGRES_HEALTH"
say "Source bot is stopped. PostgreSQL is available."

stage "Inspect source data and identities"
PI_MOUNT_LINE=$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/app/data/pi"}}{{printf "%s|%s|%s" .Type .Name .Source}}{{end}}{{end}}' "$BOT_CONTAINER")
[[ -n "$PI_MOUNT_LINE" ]] || fail "The selected bot no longer has an exact /app/data/pi mount."
PI_MOUNT_DELIMITERS=${PI_MOUNT_LINE//[^|]/}
(( ${#PI_MOUNT_DELIMITERS} == 2 )) \
  || fail "The selected Pi mount source contains an unsupported pipe character."
IFS='|' read -r PI_MOUNT_TYPE PI_VOLUME_NAME PI_SOURCE_PATH <<< "$PI_MOUNT_LINE"
case "$PI_MOUNT_TYPE" in
  volume) PI_MOUNT_SOURCE="$PI_VOLUME_NAME" ;;
  bind)
    [[ -d "$PI_SOURCE_PATH" ]] || fail "The selected Pi bind mount source is not a directory."
    PI_MOUNT_SOURCE="$PI_SOURCE_PATH"
    ;;
  *) fail "The Pi mount must be a Docker volume or bind mount, not $PI_MOUNT_TYPE." ;;
esac
[[ -n "$PI_MOUNT_SOURCE" ]] || fail "The selected Pi mount has no usable source."

mapfile -t BOT_NETWORKS < <(docker inspect --format '{{range $name, $_ := .NetworkSettings.Networks}}{{println $name}}{{end}}' "$BOT_CONTAINER" | sed '/^$/d')
mapfile -t POSTGRES_NETWORKS < <(docker inspect --format '{{range $name, $_ := .NetworkSettings.Networks}}{{println $name}}{{end}}' "$POSTGRES_CONTAINER" | sed '/^$/d')
SHARED_NETWORKS=()
for bot_network in "${BOT_NETWORKS[@]}"; do
  for postgres_network in "${POSTGRES_NETWORKS[@]}"; do
    [[ "$bot_network" == "$postgres_network" ]] && SHARED_NETWORKS+=("$bot_network")
  done
done
(( ${#SHARED_NETWORKS[@]} > 0 )) || fail "The selected bot and PostgreSQL containers do not share a Docker network."
choose_value "Choose the shared database network:" "${SHARED_NETWORKS[@]}"
SOURCE_NETWORK="$SELECTED_VALUE"

DB_URL=$(container_env_value "$BOT_CONTAINER" DB_URL || true)
BOT_TOKEN=$(container_env_value "$BOT_CONTAINER" BOT_TOKEN || true)
if [[ -z "$DB_URL" ]]; then
  ask_secret DB_URL "Paste the old bot's PostgreSQL DB_URL:"
fi
if [[ -z "$BOT_TOKEN" ]]; then
  ask_secret BOT_TOKEN "Paste the old bot's BOT_TOKEN:"
fi
[[ -n "$DB_URL" ]] || fail "DB_URL is required."
[[ -n "$BOT_TOKEN" ]] || fail "BOT_TOKEN is required."

APP_UID=$(container_env_value "$BOT_CONTAINER" APP_UID || true)
APP_GID=$(container_env_value "$BOT_CONTAINER" APP_GID || true)
E2B_DEPLOYMENT_ID=$(container_env_value "$BOT_CONTAINER" E2B_DEPLOYMENT_ID || true)
if [[ -z "$E2B_DEPLOYMENT_ID" ]]; then
  E2B_DEPLOYMENT_ID=$(container_env_value "$BOT_CONTAINER" OPEN_SANDBOX_DEPLOYMENT_ID || true)
fi
BROWSER_USE_DEPLOYMENT_ID=$(container_env_value "$BOT_CONTAINER" BROWSER_USE_DEPLOYMENT_ID || true)
: "${APP_UID:=1000}"
: "${APP_GID:=1000}"
: "${E2B_DEPLOYMENT_ID:=ai-tg-bot}"
: "${BROWSER_USE_DEPLOYMENT_ID:=ai-tg-bot}"
[[ "$APP_UID" =~ ^[1-9][0-9]*$ ]] || fail "The source APP_UID must be a positive number."
[[ "$APP_GID" =~ ^[1-9][0-9]*$ ]] || fail "The source APP_GID must be a positive number."
[[ "$E2B_DEPLOYMENT_ID" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$ ]] \
  || fail "The source E2B deployment identity is invalid."
[[ "$BROWSER_USE_DEPLOYMENT_ID" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$ ]] \
  || fail "The source Browser Use deployment identity is invalid."

PI_COMPARE_PATH="$PI_SOURCE_PATH"
if [[ -n "$PI_COMPARE_PATH" && -d "$PI_COMPARE_PATH" ]]; then
  PI_COMPARE_PATH=$(CDPATH='' cd -- "$PI_COMPARE_PATH" && pwd -P)
  path_overlaps "$EXPORT_DIR" "$PI_COMPARE_PATH" \
    && fail "The export folder must not overlap the source Pi mount."
fi

PI_AUDIT_MOUNT=$(mount_spec "$PI_MOUNT_TYPE" "$PI_MOUNT_SOURCE" /app/data/pi)
PI_ARCHIVE_MOUNT=$(mount_spec "$PI_MOUNT_TYPE" "$PI_MOUNT_SOURCE" /source ",readonly")
say "Pi source: $PI_MOUNT_TYPE $PI_MOUNT_SOURCE"
say "Database network: $SOURCE_NETWORK"
say "Application identity: UID $APP_UID, GID $APP_GID"

stage "Create and verify the three files"
say "This can take several minutes. The source bot will remain stopped."
docker build --tag "$AUDIT_IMAGE" "$REPO_ROOT"

if ! docker run --rm \
  --mount "$PI_ARCHIVE_MOUNT" \
  --entrypoint sh \
  "$AUDIT_IMAGE" \
  -eu -c 'test ! -e /source/upgrade-baseline.json.verified'; then
  fail "The source Pi volume contains upgrade-baseline.json.verified. Refusing to export an already verified target."
fi

SECRET_DIR=$(mktemp -d "${TMPDIR:-/tmp}/ai-tg-bot-export-secrets.XXXXXX")
chmod 700 "$SECRET_DIR"
umask 077
printf '%s' "$DB_URL" > "$SECRET_DIR/db-url"
printf '%s' "$BOT_TOKEN" > "$SECRET_DIR/bot-token"
: > "$SECRET_DIR/pg-service.conf"
HOST_UID=$(id -u)
HOST_GID=$(id -g)

docker run --rm \
  --mount "type=bind,source=$SECRET_DIR,target=/run/secrets" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c '
    chown "$1:$2" /run/secrets
    chmod 750 /run/secrets
    chown "$1:$2" /run/secrets/db-url /run/secrets/bot-token
    chmod 440 /run/secrets/db-url /run/secrets/bot-token
    chown "$3:$2" /run/secrets/pg-service.conf
    chmod 600 /run/secrets/pg-service.conf
  ' sh "$HOST_UID" "$APP_GID" "$APP_UID"

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "type=bind,source=$SECRET_DIR,target=/run/secrets" \
  -e DB_URL_FILE=/run/secrets/db-url \
  --entrypoint node \
  "$AUDIT_IMAGE" \
  dist/scripts/upgrade-export-connection.js --out /run/secrets/pg-service.conf

SERVER_VERSION_NUM=$(docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --network "$SOURCE_NETWORK" \
  --mount "type=bind,source=$SECRET_DIR,target=/run/secrets,readonly" \
  -e PGSERVICEFILE=/run/secrets/pg-service.conf \
  "$POSTGRES_CLIENT_IMAGE" \
  psql --dbname=service=upgrade --no-password --tuples-only --no-align \
    --set=ON_ERROR_STOP=1 --command 'show server_version_num')
SERVER_VERSION_NUM=${SERVER_VERSION_NUM//[[:space:]]/}
[[ "$SERVER_VERSION_NUM" =~ ^[0-9]+$ ]] || fail "PostgreSQL returned an invalid server version."
(( SERVER_VERSION_NUM / 10000 <= 17 )) \
  || fail "The source PostgreSQL server is newer than the pinned version 17 export client."

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --network "$SOURCE_NETWORK" \
  --mount "$PI_AUDIT_MOUNT" \
  --mount "type=bind,source=$SECRET_DIR,target=/run/secrets,readonly" \
  -e DB_URL_FILE=/run/secrets/db-url \
  -e BOT_TOKEN_FILE=/run/secrets/bot-token \
  -e "E2B_DEPLOYMENT_ID=$E2B_DEPLOYMENT_ID" \
  -e "BROWSER_USE_DEPLOYMENT_ID=$BROWSER_USE_DEPLOYMENT_ID" \
  -e PI_CODING_AGENT_DIR=/app/data/pi \
  --entrypoint node \
  "$AUDIT_IMAGE" \
  dist/scripts/upgrade-audit.js snapshot --out /app/data/pi/upgrade-baseline.json

mkdir "$EXPORT_DIR"
docker run --rm \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c 'chown "$1:$2" /backup && chmod 770 /backup' sh "$HOST_UID" "$APP_GID"

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --network "$SOURCE_NETWORK" \
  --mount "type=bind,source=$SECRET_DIR,target=/run/secrets,readonly" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  -e PGSERVICEFILE=/run/secrets/pg-service.conf \
  "$POSTGRES_CLIENT_IMAGE" \
  pg_dump --dbname=service=upgrade --format=custom --no-owner --no-acl \
    --file=/backup/.aibot.dump.partial

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup,readonly" \
  "$POSTGRES_CLIENT_IMAGE" \
  pg_restore --list /backup/.aibot.dump.partial >/dev/null

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "$PI_ARCHIVE_MOUNT" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  "$ARCHIVE_IMAGE" \
  tar -C /source -czpf /backup/.pi-home.tgz.partial .

if ! docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup,readonly" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c '
    archive=/backup/.pi-home.tgz.partial
    tar -tzf "$archive" >/dev/null
    tar -tzvf "$archive" | awk '\''{ type=substr($0,1,1); if (type != "-" && type != "d") exit 1 }'\''
    tar -tzf "$archive" | grep -Fx "./upgrade-baseline.json" >/dev/null
    if tar -tzf "$archive" | grep -Fx "./upgrade-baseline.json.verified" >/dev/null; then exit 1; fi
  '; then
  fail "The Pi archive is unreadable, unsafe, missing its baseline, or contains a stale verification marker."
fi

mv "$EXPORT_DIR/.aibot.dump.partial" "$EXPORT_DIR/aibot.dump"
mv "$EXPORT_DIR/.pi-home.tgz.partial" "$EXPORT_DIR/pi-home.tgz"
(
  cd "$EXPORT_DIR"
  sha256sum aibot.dump pi-home.tgz > .SHA256SUMS.partial
  sha256sum --check .SHA256SUMS.partial
  mv .SHA256SUMS.partial SHA256SUMS
)

docker run --rm \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c '
    chown "$1:$2" /backup/aibot.dump /backup/pi-home.tgz /backup/SHA256SUMS
    chmod 600 /backup/aibot.dump /backup/pi-home.tgz /backup/SHA256SUMS
    chmod 700 /backup
  ' sh "$HOST_UID" "$HOST_GID"
EXPORT_SUCCEEDED=1
say "Verified: aibot.dump"
say "Verified: pi-home.tgz"
say "Verified: SHA256SUMS"

stage "Keep the source stopped"
say "Upload only these three files from:"
say "$EXPORT_DIR"
printf '\n'
printf '  UPGRADE_MODE=import\n'
printf '  BOT_TOKEN=<same token as the old bot>\n'
printf '  DB_URL=<new Dokploy PostgreSQL URL>\n'
printf '  PI_CODING_AGENT_DIR=/app/data/pi\n'
printf '  UPGRADE_BASELINE_FILE=/app/data/pi/upgrade-baseline.json\n'
printf '  E2B_DEPLOYMENT_ID=%s\n' "$E2B_DEPLOYMENT_ID"
printf '  BROWSER_USE_DEPLOYMENT_ID=%s\n' "$BROWSER_USE_DEPLOYMENT_ID"
printf '  APP_UID=%s\n' "$APP_UID"
printf '  APP_GID=%s\n' "$APP_GID"
printf '\n'
say "After uploading, run this in Dokploy Advanced → Run Command:"
say "./docker/import-migration.sh"
warn "Do not restart the old bot while the Dokploy bot is running with the same token."
pause "Press Enter to finish."

finish
printf 'Migration export ready:\n  %s\n\n' "$EXPORT_DIR"
printf 'Next: upload aibot.dump, pi-home.tgz, and SHA256SUMS to /app/data/import in Dokploy.\n'
