#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

REPO_ROOT=$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE=/dev/null
ARCHIVE_IMAGE="${ARCHIVE_IMAGE:-alpine:3.22}"
AUDIT_IMAGE="ai-tg-bot-upgrade-audit:export-$$"
SECRET_DIR=""
EXPORT_DIR=""
EXPORT_SUCCEEDED=0
SELECTED_VALUE=""

fail() {
  printf '\n%sERROR:%s %s\n' "$RED" "$RESET" "$1" >&2
  exit 1
}

migration_banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "Unraid to Dokploy migration export" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '  This wizard reads the stopped bot data and creates one verified, ready-to-run\n'
  printf '  app-data archive. It never starts or stops a container.\n'
  pause "Ready to start?"
}

cleanup() {
  local status=$?
  if [[ -n "$SECRET_DIR" && -d "$SECRET_DIR" ]]; then
    rm -f -- \
      "$SECRET_DIR/bot-token"
    rmdir -- "$SECRET_DIR" 2>/dev/null || true
  fi
  if [[ "$EXPORT_SUCCEEDED" != "1" && -n "$EXPORT_DIR" && -d "$EXPORT_DIR" ]]; then
    rm -f -- \
      "$EXPORT_DIR/.baseline.json" \
      "$EXPORT_DIR/.pi-copy.tgz" \
      "$EXPORT_DIR/.app-data.tgz.partial" \
      "$EXPORT_DIR/.SHA256SUMS.partial" \
      "$EXPORT_DIR/app-data.tgz" \
      "$EXPORT_DIR/SHA256SUMS"
    rm -rf -- "$EXPORT_DIR/app-data"
    rmdir -- "$EXPORT_DIR" 2>/dev/null || true
  fi
  if [[ "$status" -ne 0 ]]; then
    printf '\nExport stopped. The wizard did not start or remove either source container.\n' >&2
  fi
  return "$status"
}

trap cleanup EXIT
trap 'exit 130' INT TERM

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required on the Unraid host."
}

container_env_value() {
  local container="$1" key="$2" line
  while IFS= read -r line; do
    if [[ "$line" == "$key="* ]]; then
      printf '%s' "${line#*=}"
      return 0
    fi
  done < <(docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' "$container")
  return 1
}

choose_value() {
  local prompt="$1"
  shift
  local values=("$@") choice index
  (( ${#values[@]} > 0 )) || fail "No choices are available for ${prompt}."
  printf '\n  %s\n' "$prompt"
  for index in "${!values[@]}"; do
    printf '    %s) %s\n' "$((index + 1))" "${values[$index]}"
  done
  if (( ${#values[@]} == 1 )); then
    printf '  Select [1]: '
  else
    printf '  Select [1-%s]: ' "${#values[@]}"
  fi
  read -r choice || true
  [[ -n "$choice" ]] || choice=1
  [[ "$choice" =~ ^[0-9]+$ ]] || fail "Selection must be a number."
  (( choice >= 1 && choice <= ${#values[@]} )) || fail "Selection is outside the displayed range."
  SELECTED_VALUE="${values[$((choice - 1))]}"
}

container_summary() {
  docker inspect --format '{{.Name}} | {{.Config.Image}} | {{.State.Status}}' "$1" | sed 's#^/##'
}

path_overlaps() {
  local left="${1%/}/" right="${2%/}/"
  [[ "$left" == "$right"* || "$right" == "$left"* ]]
}

mount_spec() {
  local type="$1" source="$2" target="$3" mode="${4:-}"
  [[ "$source" != *","* && "$source" != *$'\n'* ]] \
    || fail "The selected mount source contains a character Docker --mount cannot represent safely."
  printf 'type=%s,source=%s,target=%s%s' "$type" "$source" "$target" "$mode"
}

if (( $# != 0 )); then
  printf '%s\n' "Usage: bash scripts/unraid-migration-wizard.sh" >&2
  exit 2
fi

migration_banner

stage "Check the Unraid host"
say "The old bot must already be stopped. This export reads its SQLite database and Pi directory."
require_command docker
require_command sha256sum
docker info >/dev/null 2>&1 || fail "Docker is unavailable. Run this from an Unraid terminal with Docker access."
[[ -f "$REPO_ROOT/Dockerfile" && -f "$REPO_ROOT/scripts/upgrade-audit.ts" ]] \
  || fail "Run the wizard from a complete migration-branch checkout."
printf '  Export parent folder [%s]: ' "$PWD"
read -r export_parent_input || true
[[ -n "$export_parent_input" ]] || export_parent_input="$PWD"
[[ -d "$export_parent_input" && -w "$export_parent_input" ]] \
  || fail "The export parent folder must already exist and be writable."
EXPORT_PARENT=$(CDPATH='' cd -- "$export_parent_input" && pwd -P)
EXPORT_DIR="$EXPORT_PARENT/ai-tg-bot-migration-$(date -u +%Y%m%dT%H%M%SZ)"
[[ "$EXPORT_DIR" != *","* && "$EXPORT_DIR" != *$'\n'* ]] \
  || fail "The export path must not contain a comma or newline."
[[ ! -e "$EXPORT_DIR" ]] || fail "The timestamped export directory already exists. Wait one second and rerun."
say "Export folder: $EXPORT_DIR"

stage "Select the old containers"
mapfile -t ALL_CONTAINERS < <(docker ps -a --format '{{.Names}}')
(( ${#ALL_CONTAINERS[@]} > 0 )) || fail "Docker has no containers to inspect."
BOT_CANDIDATES=()
for container in "${ALL_CONTAINERS[@]}"; do
  if [[ "$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/app/data"}}yes{{end}}{{end}}' "$container")" == *yes* ]]; then
    BOT_CANDIDATES+=("$container")
  fi
done
(( ${#BOT_CANDIDATES[@]} > 0 )) \
  || fail "No container has the expected /app/data appdata mount."

BOT_CHOICES=()
for container in "${BOT_CANDIDATES[@]}"; do BOT_CHOICES+=("$(container_summary "$container")"); done
choose_value "Choose the stopped ai-tg-bot container:" "${BOT_CHOICES[@]}"
BOT_CHOICE="$SELECTED_VALUE"
for index in "${!BOT_CHOICES[@]}"; do
  [[ "${BOT_CHOICES[$index]}" == "$BOT_CHOICE" ]] && BOT_CONTAINER="${BOT_CANDIDATES[$index]}"
done

[[ "$(docker inspect --format '{{.State.Running}}' "$BOT_CONTAINER")" == "false" ]] \
  || fail "The selected bot is still running. Stop it in the Unraid UI, then rerun the wizard."
say "Source bot is stopped."

stage "Inspect source data and identities"
APPDATA_MOUNT_LINE=$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/app/data"}}{{printf "%s|%s|%s" .Type .Name .Source}}{{end}}{{end}}' "$BOT_CONTAINER")
[[ -n "$APPDATA_MOUNT_LINE" ]] || fail "The selected bot no longer has an exact /app/data mount."
APPDATA_MOUNT_DELIMITERS=${APPDATA_MOUNT_LINE//[^|]/}
(( ${#APPDATA_MOUNT_DELIMITERS} == 2 )) \
  || fail "The selected appdata mount source contains an unsupported pipe character."
IFS='|' read -r APPDATA_MOUNT_TYPE APPDATA_VOLUME_NAME APPDATA_SOURCE_PATH <<< "$APPDATA_MOUNT_LINE"
case "$APPDATA_MOUNT_TYPE" in
  volume) APPDATA_MOUNT_SOURCE="$APPDATA_VOLUME_NAME" ;;
  bind)
    [[ -d "$APPDATA_SOURCE_PATH" ]] || fail "The selected appdata bind mount source is not a directory."
    APPDATA_MOUNT_SOURCE="$APPDATA_SOURCE_PATH"
    ;;
  *) fail "The appdata mount must be a Docker volume or bind mount, not $APPDATA_MOUNT_TYPE." ;;
esac
[[ -n "$APPDATA_MOUNT_SOURCE" ]] || fail "The selected appdata mount has no usable source."

DB_URL=$(container_env_value "$BOT_CONTAINER" DB_URL || true)
BOT_TOKEN=$(container_env_value "$BOT_CONTAINER" BOT_TOKEN || true)
: "${DB_URL:=sqlite:/app/data/bot.db}"
case "$DB_URL" in
  sqlite:/app/data/bot.db|sqlite:./data/bot.db) DB_URL=sqlite:/app/data/bot.db ;;
  *) fail "The selected bot must use SQLite at /app/data/bot.db, but DB_URL is configured differently." ;;
esac
if [[ -z "$BOT_TOKEN" ]]; then
  ask_secret BOT_TOKEN "Paste the old bot's BOT_TOKEN:"
fi
[[ -n "$BOT_TOKEN" ]] || fail "BOT_TOKEN is required."

PI_CODING_AGENT_DIR=$(container_env_value "$BOT_CONTAINER" PI_CODING_AGENT_DIR || true)
: "${PI_CODING_AGENT_DIR:=/app/data/pi}"
case "$PI_CODING_AGENT_DIR" in
  /app/data/pi|./data/pi) PI_CODING_AGENT_DIR=/app/data/pi ;;
  *) fail "The selected bot must keep Pi state at /app/data/pi, but PI_CODING_AGENT_DIR is configured differently." ;;
esac

PI_MOUNT_LINE=$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/app/data/pi"}}{{printf "%s|%s|%s" .Type .Name .Source}}{{end}}{{end}}' "$BOT_CONTAINER")
PI_MOUNT_TYPE=""
PI_MOUNT_SOURCE=""
PI_SOURCE_PATH=""
if [[ -n "$PI_MOUNT_LINE" ]]; then
  PI_MOUNT_DELIMITERS=${PI_MOUNT_LINE//[^|]/}
  (( ${#PI_MOUNT_DELIMITERS} == 2 )) \
    || fail "The selected Pi mount source contains an unsupported pipe character."
  IFS='|' read -r PI_MOUNT_TYPE PI_VOLUME_NAME PI_SOURCE_PATH <<< "$PI_MOUNT_LINE"
  case "$PI_MOUNT_TYPE" in
    volume) PI_MOUNT_SOURCE="$PI_VOLUME_NAME" ;;
    bind)
      [[ -d "$PI_SOURCE_PATH" ]] || fail "The selected Pi bind mount source is not a directory."
      PI_MOUNT_SOURCE="$PI_SOURCE_PATH"
      ;;
    *) fail "The Pi mount must be a Docker volume or bind mount, not $PI_MOUNT_TYPE." ;;
  esac
  [[ -n "$PI_MOUNT_SOURCE" ]] || fail "The selected Pi mount has no usable source."
fi

APP_UID=$(container_env_value "$BOT_CONTAINER" APP_UID || true)
APP_GID=$(container_env_value "$BOT_CONTAINER" APP_GID || true)
E2B_DEPLOYMENT_ID=$(container_env_value "$BOT_CONTAINER" E2B_DEPLOYMENT_ID || true)
if [[ -z "$E2B_DEPLOYMENT_ID" ]]; then
  E2B_DEPLOYMENT_ID=$(container_env_value "$BOT_CONTAINER" OPEN_SANDBOX_DEPLOYMENT_ID || true)
fi
BROWSER_USE_DEPLOYMENT_ID=$(container_env_value "$BOT_CONTAINER" BROWSER_USE_DEPLOYMENT_ID || true)
: "${APP_UID:=1000}"
: "${APP_GID:=1000}"
: "${E2B_DEPLOYMENT_ID:=ai-tg-bot}"
: "${BROWSER_USE_DEPLOYMENT_ID:=ai-tg-bot}"
[[ "$APP_UID" =~ ^[1-9][0-9]*$ ]] || fail "The source APP_UID must be a positive number."
[[ "$APP_GID" =~ ^[1-9][0-9]*$ ]] || fail "The source APP_GID must be a positive number."
[[ "$E2B_DEPLOYMENT_ID" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$ ]] \
  || fail "The source E2B deployment identity is invalid."
[[ "$BROWSER_USE_DEPLOYMENT_ID" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]*$ ]] \
  || fail "The source Browser Use deployment identity is invalid."

APPDATA_COMPARE_PATH="$APPDATA_SOURCE_PATH"
if [[ -n "$APPDATA_COMPARE_PATH" && -d "$APPDATA_COMPARE_PATH" ]]; then
  APPDATA_COMPARE_PATH=$(CDPATH='' cd -- "$APPDATA_COMPARE_PATH" && pwd -P)
  path_overlaps "$EXPORT_DIR" "$APPDATA_COMPARE_PATH" \
    && fail "The export folder must not overlap the source appdata mount."
fi
if [[ "$PI_MOUNT_TYPE" == "bind" ]]; then
  PI_COMPARE_PATH=$(CDPATH='' cd -- "$PI_SOURCE_PATH" && pwd -P)
  path_overlaps "$EXPORT_DIR" "$PI_COMPARE_PATH" \
    && fail "The export folder must not overlap the source Pi mount."
fi

APPDATA_READONLY_MOUNT=$(mount_spec "$APPDATA_MOUNT_TYPE" "$APPDATA_MOUNT_SOURCE" /source ",readonly")
SOURCE_READONLY_MOUNTS=(--mount "$APPDATA_READONLY_MOUNT")
SOURCE_PI_PATH=/source/pi
if [[ -n "$PI_MOUNT_SOURCE" ]]; then
  SOURCE_PI_PATH=/source-pi
  PI_READONLY_MOUNT=$(mount_spec "$PI_MOUNT_TYPE" "$PI_MOUNT_SOURCE" "$SOURCE_PI_PATH" ",readonly")
  SOURCE_READONLY_MOUNTS+=(--mount "$PI_READONLY_MOUNT")
fi
if ! docker run --rm \
  "${SOURCE_READONLY_MOUNTS[@]}" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c 'test -f /source/bot.db && test ! -L /source/bot.db && test -d "$1" && test ! -L "$1"' sh "$SOURCE_PI_PATH"; then
  fail "The selected source mounts must contain the regular paths bot.db and pi/."
fi

LEGACY_DATA_LINE=$(docker inspect --format '{{range .Mounts}}{{if eq .Destination "/app/data/files"}}{{printf "%s|%s|%s" .Type .Name .Source}}{{end}}{{end}}' "$BOT_CONTAINER")
say "Appdata source: $APPDATA_MOUNT_TYPE $APPDATA_MOUNT_SOURCE"
if [[ -n "$PI_MOUNT_SOURCE" ]]; then
  say "Pi source: $PI_MOUNT_TYPE $PI_MOUNT_SOURCE"
fi
if [[ -n "$LEGACY_DATA_LINE" ]]; then
  LEGACY_DATA_SOURCE=${LEGACY_DATA_LINE##*|}
  say "Legacy managed-file source excluded from export: $LEGACY_DATA_SOURCE"
fi
say "Application identity: UID $APP_UID, GID $APP_GID"

stage "Create ready-to-run app data"
say "This can take several minutes. The source bot will remain stopped."
docker build --tag "$AUDIT_IMAGE" "$REPO_ROOT"

SECRET_DIR=$(mktemp -d "${TMPDIR:-/tmp}/ai-tg-bot-export-secrets.XXXXXX")
chmod 700 "$SECRET_DIR"
umask 077
printf '%s' "$BOT_TOKEN" > "$SECRET_DIR/bot-token"
HOST_UID=$(id -u)
HOST_GID=$(id -g)

docker run --rm \
  --mount "type=bind,source=$SECRET_DIR,target=/run/secrets" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c '
    chown "$1:$2" /run/secrets
    chmod 750 /run/secrets
    chown "$3:$2" /run/secrets/bot-token
    chmod 440 /run/secrets/bot-token
  ' sh "$HOST_UID" "$APP_GID" "$APP_UID"

mkdir "$EXPORT_DIR"
docker run --rm \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c '
    chown "$1:$2" /backup
    chmod 770 /backup
    mkdir -p /backup/app-data/pi
    chown -R "$3:$2" /backup/app-data
    chmod 700 /backup/app-data /backup/app-data/pi
  ' sh "$HOST_UID" "$APP_GID" "$APP_UID"

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  "${SOURCE_READONLY_MOUNTS[@]}" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  -e DB_URL=sqlite:/source/bot.db \
  --entrypoint node \
  "$AUDIT_IMAGE" \
  dist/scripts/upgrade-export-sqlite.js --out /backup/app-data/bot.db

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  "${SOURCE_READONLY_MOUNTS[@]}" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  "$ARCHIVE_IMAGE" \
  tar -C "$SOURCE_PI_PATH" -czpf /backup/.pi-copy.tgz .

if ! docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup,readonly" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c '
    archive=/backup/.pi-copy.tgz
    tar -tzf "$archive" >/dev/null
    tar -tzvf "$archive" | awk '\''{ type=substr($0,1,1); if (type != "-" && type != "d") exit 1 }'\''
  '; then
  fail "The Pi directory contains an unreadable file, symbolic link, or unsupported entry."
fi

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  "$ARCHIVE_IMAGE" \
  tar -C /backup/app-data/pi -xzpf /backup/.pi-copy.tgz
rm -f -- "$EXPORT_DIR/.pi-copy.tgz"

TARGET_APPDATA_MOUNT="type=bind,source=$EXPORT_DIR/app-data,target=/app/data"
docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "$TARGET_APPDATA_MOUNT" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  --mount "type=bind,source=$SECRET_DIR,target=/run/secrets,readonly" \
  -e DB_URL=sqlite:/app/data/bot.db \
  -e BOT_TOKEN_FILE=/run/secrets/bot-token \
  -e "E2B_DEPLOYMENT_ID=$E2B_DEPLOYMENT_ID" \
  -e "BROWSER_USE_DEPLOYMENT_ID=$BROWSER_USE_DEPLOYMENT_ID" \
  -e PI_CODING_AGENT_DIR=/app/data/pi \
  --entrypoint node \
  "$AUDIT_IMAGE" \
  dist/scripts/upgrade-audit.js snapshot --out /backup/.baseline.json

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "$TARGET_APPDATA_MOUNT" \
  --entrypoint node \
  "$AUDIT_IMAGE" \
  dist/scripts/prepare-migration-data.js --data /app/data

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "$TARGET_APPDATA_MOUNT" \
  --mount "type=bind,source=$EXPORT_DIR,target=/audit,readonly" \
  --mount "type=bind,source=$SECRET_DIR,target=/run/secrets,readonly" \
  -e DB_URL=sqlite:/app/data/bot.db \
  -e BOT_TOKEN_FILE=/run/secrets/bot-token \
  -e "E2B_DEPLOYMENT_ID=$E2B_DEPLOYMENT_ID" \
  -e "BROWSER_USE_DEPLOYMENT_ID=$BROWSER_USE_DEPLOYMENT_ID" \
  -e PI_CODING_AGENT_DIR=/app/data/pi \
  --entrypoint node \
  "$AUDIT_IMAGE" \
  dist/scripts/upgrade-audit.js verify --against /audit/.baseline.json

docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  "$ARCHIVE_IMAGE" \
  tar -C /backup/app-data -czpf /backup/.app-data.tgz.partial .

if ! docker run --rm \
  --user "$APP_UID:$APP_GID" \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup,readonly" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c '
    archive=/backup/.app-data.tgz.partial
    tar -tzf "$archive" >/dev/null
    tar -tzvf "$archive" | awk '\''{ type=substr($0,1,1); if (type != "-" && type != "d") exit 1 }'\''
    tar -tzf "$archive" | grep -Fx "./bot.db" >/dev/null
    tar -tzf "$archive" | grep -Fx "./pi/" >/dev/null
    if tar -tzf "$archive" | grep -E "^\\./bot\\.db-(wal|shm)$" >/dev/null; then exit 1; fi
  '; then
  fail "The prepared app-data archive is unreadable, unsafe, or incomplete."
fi

mv "$EXPORT_DIR/.app-data.tgz.partial" "$EXPORT_DIR/app-data.tgz"
(
  cd "$EXPORT_DIR"
  sha256sum app-data.tgz > .SHA256SUMS.partial
  sha256sum --check .SHA256SUMS.partial
  mv .SHA256SUMS.partial SHA256SUMS
)

rm -f -- "$EXPORT_DIR/.baseline.json"
rm -rf -- "$EXPORT_DIR/app-data"

docker run --rm \
  --mount "type=bind,source=$EXPORT_DIR,target=/backup" \
  "$ARCHIVE_IMAGE" \
  sh -eu -c '
    chown "$1:$2" /backup/app-data.tgz /backup/SHA256SUMS
    chmod 600 /backup/app-data.tgz /backup/SHA256SUMS
    chmod 700 /backup
  ' sh "$HOST_UID" "$HOST_GID"
EXPORT_SUCCEEDED=1
say "Verified: app-data.tgz"
say "Verified: SHA256SUMS"

stage "Keep the source stopped"
say "Upload the prepared archive from:"
say "$EXPORT_DIR"
printf '\n'
printf '  BOT_TOKEN=<same token as the old bot>\n'
printf '  DB_URL=sqlite:/app/data/bot.db\n'
printf '  PI_CODING_AGENT_DIR=/app/data/pi\n'
printf '  E2B_DEPLOYMENT_ID=%s\n' "$E2B_DEPLOYMENT_ID"
printf '  BROWSER_USE_DEPLOYMENT_ID=%s\n' "$BROWSER_USE_DEPLOYMENT_ID"
printf '  APP_UID=%s\n' "$APP_UID"
printf '  APP_GID=%s\n' "$APP_GID"
printf '\n'
say "Unpack app-data.tgz into the empty /app/data volume, then start the bot normally."
warn "Do not restart the old bot while the Dokploy bot is running with the same token."
pause "Press Enter to finish."

finish
printf 'Migration export ready:\n  %s\n\n' "$EXPORT_DIR"
printf 'Next: restore app-data.tgz into the empty /app/data volume, then start the Dokploy bot.\n'
